# dbt profile yaml file with multiple environments
stacktonic_example_project:
 target: dev
 outputs:
  dev:
   type: bigquery
   method: oauth
   project: sig-chi-picks
   dataset: test_ga4
   threads: 1
   timeout_seconds: 300
   location: US
   priority: interactive
   retries: 1
  prod:
   type: bigquery
   method: oauth
   project: sig-chi-picks
   dataset: test_ga4
   threads: 5
   timeout_seconds: 300
   location: US
   priority: interactive
   retries: 1